apiVersion: v1
kind: Service
metadata:
  name: snapverse-ai-service
  namespace: snapverse
  labels:
    app: snapverse-ai
spec:
  type: LoadBalancer
  selector:
    app: snapverse-ai
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
